LiberFitProject/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^library/', include('library.urls')),
    url(r'^select2/', include('django_select2.urls')),
    url(r'^admin/', admin.site.urls),
]

library/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^index$', views.index, name='index'),
    url(r'^books$', views.books),
    url(r'^authors_list', views.authors_list),
    url(r'^(?P<author_id>\d+)$', views.author_page)
]

library/models.py
from django.db import models


class Genre(models.Model):
    name = models.CharField(max_length=30)

    def __str__(self):
        return self.name


class Author(models.Model):
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)
    date_of_birth = models.DateField('Date of birth')

    class Meta:
        ordering = ['last_name']

    def __str__(self):
        return self.first_name + ' ' + self.last_name


class Book(models.Model):
    title = models.CharField(max_length=50)
    author = models.ManyToManyField(Author)
    genre = models.ManyToManyField(Genre)
    page_number = models.IntegerField()
    publishing_date = models.DateField('Date of publication')
    front_cover = models.ImageField(default="./pictures/no-image-available.png")

    class Meta:
        ordering = ['publishing_date']

    def __str__(self):
        return self.title + ' (' + str(self.publishing_date.__format__("%Y")) + ')'

library/views.py
from django.http import HttpResponse
from django.template import loader

from library.models import Author
from .models import Book


def index(request):
    return HttpResponse("Hello World")


def books(request):
    books_list = Book.objects.all()
    template = loader.get_template('library/books_list.html')
    context = {'books': books_list}
    return HttpResponse(template.render(context, request))


def authors_list(request):
    authors_list = Author.objects.all()
    template = loader.get_template('library/authors_list.html')
    context = {'authors_list': authors_list}
    return HttpResponse(template.render(context, request))


def author_page(request, author_id):
    author = Author.objects.get(pk=author_id)
    books_list = Book.objects.all()
    template = loader.get_template('library/author_page.html')
    context = {
        'author': author,
        'books': books_list
       }
    return HttpResponse(template.render(context, request))

templates/library/author_page.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
          integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
          crossorigin="anonymous">
    <title>{{ author.first_name }} {{ author.last_name }}</title>
</head>
<body>
    <div class="jumbotron text-center">
        <h1>{{ author.first_name }} {{ author.last_name }}</h1>
        <p>{{ author.date_of_birth }}</p>
    </div>
    <div class="container" style="padding-left: 100px;padding-right: 100px;">
        {% for book in author.book_set.all %}
            <ul class="list-group-item d-flex justify-content-between align-items-center">
                <li>
                    {{ book.title }} - {{ book.publishing_date | date:"Y" }}
                    <span class="badge badge-secondary badge-pill">{{ book.page_number}} pages</span>
                </li>
            </ul>
        {% endfor %}
    </div>
</body>
</html>

templates/library/authors_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
          integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
          crossorigin="anonymous">
    <title>Authors</title>
</head>
<body>
    <div class="jumbotron text-center">
        <h1>Authors</h1>
        <p>List of every author</p>
    </div>
    <div class="container" style="padding-left: 100px;padding-right: 100px;">
        {% for author in authors_list %}
            <ul class="list-group">
                <li class="list-group-item d-flex justify-content-between align-items-center">
                    <a href="{{ author.id }}">{{ author }}</a>
                    <span class="badge badge-primary badge-pill"> {{ author.book_set.all.count }} books</span>
                </li>
            </ul>
        {% endfor %}
    </div>
</body>
</html>

templates/library/books_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
          integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
          crossorigin="anonymous">
    <title>Books</title>
</head>
<body>
    <div class="jumbotron text-center">
        <h1>Books</h1>
        <p>List of every book</p>
    </div>

    <div class="container" style="padding-left: 100px;padding-right: 100px;">
        {% for book in books %}
            <ul>
                <li class="list-group">
                    {{ book.title }} - {{ book.publishing_date | date:"Y"}}
                </li>
            </ul>
        {% endfor %}
    </div>

</body>
</html>